### ISSUE TITLE
Config values getting stringified

### ISSUE THREAD

**Issue by dinshaw** [jedcn/reveal-ck#25]
The title-footer plugin : https://github.com/e-gor/Reveal.js-Title-Footer requires the following in the config: 

config.yml
```yml
revealjs_config:
  dependencies:
    -
      src: 'plugin/title-footer/title-footer.js'
      async: true
      callback: function() { title_footer.initialize("My footer","rgba(255,255,255,0.1)"); }

```

When this gets generated, the function is stringified in index.html

```javascript
var configOptions = {"dependencies":[{"src":"plugin/title-footer/title-footer.js","async":true,"callback":"function() { title_footer.initialize('github.com/dinshaw/promise','rgba(255,255,255,0.1)'); }"}]}
```

removing the quotes from the initializer above fixes the issue.
