### ISSUE TITLE
Custom JS and css

### ISSUE THREAD

**Issue by kbrock** [jedcn/reveal-ck#46]
Could you document how to add a few custom javascript and css snippets to an existing theme (like you did with `reveal-ck.css`?

Do I need to create my own template?
Assuming I can find `night` in the `reveal-ck/files/reveal.js` directory, where would I put this?

I can the instructions into a doc if you could start me in the right direction

**Comment by jedcn** [comment]
If you're talking about CSS tweaks, you can create a `css/` directory and create a css file in it. That CSS file will be automatically included and linked up in the presentation.

It's described here:

https://relishapp.com/jedcn/reveal-ck/docs/how-to-store-and-reference-css

The docs at https://relishapp.com/jedcn/reveal-ck are generated from the `feature/*.feature` files in this repository.

I try to write up `.feature` files for every thing-- so-- if it's possible it'll be on https://relishapp.com.

**Comment by jedcn** [comment]
I've never used a reveal.js plugin or used custom JavaScript-- so-- I think I put something minimal in-- described here:

https://relishapp.com/jedcn/reveal-ck/docs/how-to-store-and-reference-js

But I've never used it.

If you can give me a use case (for something you're doing), we can work backwards to figure out how to make it happen.

**Comment by kbrock** [comment]
Worked like a charm

```css
.reveal cite {
  font-style: italic;
}
@media print {
  /* overriding .reveal section img */
  .reveal section h1 img, .reveal section h3 img {
    display: inline;
  }  
}
```
