### ISSUE TITLE
Can't customize separators

### ISSUE THREAD

**Issue by julien-leclercq** [jedcn/reveal-ck#89]
Hi ! 

I am trying to use custom separators for my slides like I would in reveal.js but it doesn't work 

What I did is append this in my `config.yml` file

```YAML
revealjs_config:
    title: Foobar
    separator: <!--s-->
    verticalSeparator: <!--v-->
    theme: solarized
    revealOptions:
        transition: 'fade'
```
